config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  get "contact", to: "pages#contact"

  resources :properties do
    resources :bookings, only: [ :new, :create ]
  end

  resources :bookings, only: [ :show, :update, :edit, :index, :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  STATUS = [ "Free", "Booked" ]

  validates :status, :start_date, :end_date, presence: true
  validates :status, inclusion: { in: STATUS, message: "Not a valid booking status" }
  validate :end_date_is_after_start_date


  belongs_to :user
  belongs_to :property

  private

  def end_date_is_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "cannot be before the start date")
    end
  end

end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  has_many :users, through: :bookings
  has_many :bookings
  has_many_attached :photos
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  CATEGORY1 = ["House", "Appartment"]
  CATEGORY2 = ["Premium", "Normal", "Simple"]
  validates :address, presence: true
  validates :size, presence: true
  validates :year, presence: true
  validates :price, presence: true
  validates :rooms, presence: true
  validates :type_of_property, presence: true
  validates :state, presence: true
  validates :state, inclusion: { in: CATEGORY2, message: "Not a valid category" }
  validates :type_of_property, inclusion: { in: CATEGORY1, message: "Not a valid category" }
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :properties
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

    def configure_permitted_parameters
        # For additional fields in app/views/devise/registrations/new.html.erb
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    
        # For additional in app/views/devise/registrations/edit.html.erb
        devise_parameter_sanitizer.permit(:account_update, keys: [:username])
      end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    skip_before_action :authenticate_user!, only: :home

    def home
    end

    def contact
    end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

  def index
    @properties = Property.all
    @properties = Property.geocoded
    @markers = @properties.geocoded.map do |property|
      {
        lat: property.latitude,
        lng: property.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { property: property }),
        image_url: helpers.asset_url('pickup.svg')
      }
    end
  end
    
  def show
    @property = Property.find(params[:id])
  end

  def new
    @property = Property.new
  end
    
  def create
    @property = Property.new(property_params)
    @property .user = current_user
    @property.save!
    redirect_to properties_path(@property)
  end

  def edit
    @property = Property.find(params[:id])
  end

  def update
    @property = Property.find(params[:id])
    @property.update(property_params)
    redirect_to properties_path(@property)
  end

  def destroy
    @property = Property.find(params[:id])
    @property.destroy
 
    redirect_to properties_path(@property)
  end

  private

  def property_params
    params.require(:property).permit(:address, :size, :year, :rooms, :price, :state, :type_of_property, photos: [])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RealEstate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/flashes' %>
    <%= render 'shared/footer' %>
  </body>
  <script>
  // Your web app's Firebase configuration
  var firebaseConfig = {
    apiKey: "AIzaSyAo70WDDKHoMVihy6Maj2JXos5dKonmZe0",
    authDomain: "real-estate-9ceeb.firebaseapp.com",
    projectId: "real-estate-9ceeb",
    storageBucket: "real-estate-9ceeb.appspot.com",
    messagingSenderId: "948551135229",
    appId: "1:948551135229:web:03fd8520eb1e1e63cef394"
  };
  // Initialize Firebase
  firebase.initializeApp(firebaseConfig);
</script>
</html>

app/views/pages/_home-banner.html.erb
<div class="banner">
    <div class="banner-content text-left">
      <%= link_to "OFFER YOUR HOME", new_property_path, class: "btn btn-lg"  %>
    </div>
</div>

app/views/pages/home.html.erb
<%= render 'home-banner' %>

<%= render 'home-middle-part' %>

app/views/properties/_form-new.html.erb
<%= simple_form_for(@property) do |f| %>


  <div class="form-inputs mb-3">
    <%= f.input :address, placeholder: "i.e. Schlossstraße"%>
    <%= f.input :size,  placeholder: "i.e. 100m2" %>
    <%= f.input :year,placeholder: "i.e. 2000" %>
    <%= f.input :rooms, placeholder: "i.e. 4" %>
    <%= f.input :price, placeholder: "i.e. 1000" %>
    <%= f.input :state, as: :select, collection: Property::CATEGORY2 %>
    <%= f.input :type_of_property, as: :select, collection: Property::CATEGORY1 %>
  </div>

  <div class="form-photos">
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  </div>

  <div class="btn">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/properties/_info_window.html.erb
<h2><%= property.address %></h2>

app/views/properties/_map.html.erb
<div id="map"
     style="width: 100%; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/properties/_show-page.html.erb
<div class="list-group">
  <div class="picture">
    <% if @property.photos.attached?%>
      <%= cl_image_tag @property.photos.first.key, height: 500, width: 400, crop: :fill %>
      <% else %>
      <%= image_tag "placeholder.jpg" %>
    <% end %>
  </div>
  <div class="info">
    <p><i>Location:</i> <%=@property.address %></p>
    <p><i>Size:</i>  <%= @property.size %></p>
    <p><i>Construction year:</i>  <%= @property.year %></p>
    <p><i>Number of rooms:</i>  <%= @property.rooms %></p>
    <p><i>Rent:</i>  <%= @property.price %>€</p>
    <p><i>State of property:</i>  <%= @property.state%></p>
    <p><i>Type of property:</i> <%= @property.type_of_property%></p>
    <hr>
    <p><%= link_to 'Delete' , property_path(property), method: :delete, class:"btn btn-dark"%><p>
    <div class="back-button"><i class="fa fa-undo" aria-hidden="true"></i> <%= link_to 'Back to properties', properties_path %></div>
  </div>
</div>

app/views/properties/edit.html.erb
<%= simple_form_for(@property) do |f| %>
  <%= f.input :address %>
  <%= f.input :size %>
  <%= f.input :year %>
  <%= f.input :rooms %>
  <%= f.input :price %>
  <%= f.input :state %>
  <%= f.input :type_of_property %>
  <%= f.submit %>
<% end %>

app/views/properties/index.html.erb
<div class="cards"> 
    <% @properties.each do |property| %>
    <div class="single-featured-property "> 
    <div class="property-thumb">
      <% if property.photos.attached?%>
        <%= cl_image_tag property.photos.first.key, crop: :fill %>
        <% else %>
        <%= image_tag "placeholder.jpg" %>
      <% end %>
      <div class="tag">
        <span>For Sale</span>
      </div>
      <div class="list-price">
        <p>€<%= property.price %></p>
      </div>
      <div class="list-view">
        <%= link_to 'View' , property_path(property)%>
      </div>
    </div>

      <div class="property-content">
        <h5>Property in </h5>
        <p class="location"><i class="fa fa-map-marker" aria-hidden="true"></i> <%= property.address %></p>
        <p>Characteristics of the property:</p>
        <div class="property-meta-data d-flex align-items-end justify-content-between">
          <div class="new-tag">
            <i class="fa fa-file" aria-hidden="true"></i>
            <span><%= property.size %></span>
          </div>
          <div class="bathroom">
            <i class="fa fa-bed" aria-hidden="true"></i>
            <span><%= property.rooms %></span>
          </div>
          <div class="garage">
            <i class="fa fa-bookmark" aria-hidden="true"></i>
            <span><%= property.state %></span>
          </div>
          <div class="space">
            <i class="fa fa-home" aria-hidden="true"></i>
            <span><%= property.type_of_property %></span>
          </div>
        </div>
      </div>
        </div>
      <% end %>
</div>
  <%# <div class="col-12 col-lg-4">
    <div class="map-div my-5">
    <%= render 'map' %>
    <%# </div>
  </div> %>

app/views/properties/new.html.erb
<div class="new-container">
  <div class="row justify-content-center mr-0">
    <div class="col-6 form-col">
      <div class="form-new">
        <h1><strong>Offer your Home</strong></h1>
        <h4>
        Let your possible renters know which kind of home you are offering by sharing the location,size, construction year, number of rooms, price , type and state of the property.Dont forget to add some beautiful pictures.</h3>
        </h4>
        <%= render 'form-new', property: @property %>
        <br>
        <div class="back-button"><i class="fa fa-undo" aria-hidden="true"></i> <%= link_to 'Back to properties', properties_path %></div>
      </div>
    </div>
  </div>
</div>

app/views/properties/show.html.erb
<div class="container my-3">
  <%= render 'show-page', property: @property %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer mt-auto py-3">
  <div class="container">

  <ul class="list-unstyled list-inline text-center">
    <li class="list-inline-item">
      <a href="https://www.facebook.com" class="btn-floating btn-fb mx-1">
        <i class="fab fa-facebook-f"> </i>
      </a>
    </li>
    <li class="list-inline-item">
      <a href="https://www.twitter.com" class="btn-floating btn-tw mx-1">
        <i class="fab fa-twitter"> </i>
      </a>
    </li>
    <li class="list-inline-item">
      <a href="https://www.instagram.com" class="btn-floating btn-li mx-1">
        <i class="fab fa-instagram"> </i>
      </a>
    </li>

    <li class="list-inline-item">
       © 2021 Copyright: New Home <i class="fas fa-heart"></i>
    </li>
  </ul>

  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://seeklogo.com/images/E/eco-house-graphics-logo-6AE63FA421-seeklogo.com.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Contact", contact_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Dashboard", properties_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://cdn.shortpixel.ai/spai/w_375+q_+ret_img+to_webp/https://afmnoco.com/wp-content/uploads/2019/07/74046195_s.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>